# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Metropolis samples using Rcpp
#' @description A Metropolis sampler using Rcpp
#' @param sigma the sample variance
#' @param x0 the given initial value
#' @param N the number of the samples
#' @return a random sample of size \code{n}
#' @useDynLib StatComp20039
#' @examples
#' \dontrun{
#' sigma = 2
#' x0 = 25
#' N = 2000
#' rwMetropolis(sigma,x0,N)
#' }
#' @export
rwMetropolis <- function(sigma, x0, N) {
    .Call('_StatComp20039_rwMetropolis', PACKAGE = 'StatComp20039', sigma, x0, N)
}

